GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Roger Ruz",
  "number": "999999999"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Roger Ruz",
  "number": "999999999"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "999999999"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Persona sin numero"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123456"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Roger Ruz",
  "number": "999999999"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mongo Test",
  "number": "123-456789"
}


###
GET http://localhost:3001/api/persons