GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Roger Ruz",
  "number": "999999999"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Roger Ruz",
  "number": "999999999"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "999999999"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Persona sin numero"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123456"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Roger Ruz",
  "number": "999999999"
}

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mongo Test",
  "number": "123-456789"
}


###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/69f2dab08f033f0fe274821f

###
GET http://localhost:3001/api/persons

###
PUT http://localhost:3001/api/persons/69f2d81bf392a9b2e86f851e
Content-Type: application/json

{
  "name": "Roger",
  "number": "999123187"
}

###
GET http://localhost:3001/api/persons

###
PUT http://localhost:3001/api/persons/PEGA_UN_ID_VALIDO
Content-Type: application/json

{
  "name": "Al",
  "number": "999999"
}